- hosts: myvms
  remote_user: superuser
  become_method: sudo
  gather_facts: no
  tasks:
          - name: Update User user1
            user:
              name: user1
              update_password: always
              groups: sudo
              append: yes
              password: "{{ 'somecomplexpass' | password_hash('sha512') }}"

          - name: Update User user2
            user:
              name: user2
              update_password: always
              groups: sudo
              append: yes
              password: "{{ 'somecomplexpass' | password_hash('sha512') }}"
